routes/web.php
<?php

use App\Http\Controllers\DBBackupController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProfilController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PenawaranController;
use App\Http\Controllers\ActionPenawaran;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\FormController;
use App\Http\Controllers\PurchaseorderController;
use App\Http\Controllers\SuratJalanController;
use App\Http\Controllers\KonsumenController;
use App\Http\Controllers\DetailPenawaranController;
use App\Http\Controllers\DetailPurchaseOrderController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application.
| These routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::permanentRedirect('/', '/login');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('profil', ProfilController::class)->except('destroy');

Route::resource('konsumen', KonsumenController::class);
Route::resource('manage-user', UserController::class);
Route::resource('manage-role', RoleController::class);
Route::resource('manage-menu', MenuController::class);
Route::resource('manage-permission', PermissionController::class)->only('store', 'destroy');
Route::resource('manage-penawaran', PenawaranController::class);
Route::resource('manage-barang', BarangController::class);
Route::get('/barang/create', [BarangController::class, 'create'])->name('barang.create');
Route::get('/barang/{id}/edit', [BarangController::class, 'edit'])->name('barang.edit');
Route::put('/barang/{barang}', [BarangController::class, 'update'])->name('barang.update');
Route::resource('/manage-purchaseorder', PurchaseorderController::class);

Route::put('/purchaseorders/{id}', [PurchaseorderController::class, 'update'])->name('purchaseorder.update');
Route::get('/purchaseorders', [PurchaseorderController::class, 'index'])->name('purchaseorder.index');
Route::get('/purchaseorders/{id}/edit', [PurchaseorderController::class, 'edit'])->name('purchaseorder.edit');
Route::post('/purchaseorders/{id}/updateType', [PurchaseorderController::class, 'updateType'])->name('purchaseorder.updateType');
Route::delete('/purchaseorders/{id}', [PurchaseorderController::class, 'destroy'])->name('purchaseorder.destroy');
Route::resource('manage-suratjalan', SuratjalanController::class);
Route::resource('manage-form', FormController::class);
Route::get('/manage-penawaran', [PenawaranController::class, 'index'])->name('penawaran.index');
Route::get('/tambahpenawaran', [PenawaranController::class, 'tambahpenawaran'])->name('penawaran.tambahpenawaran');
Route::post('/manage-penawaran', [PenawaranController::class, 'store'])->name('penawaran.store');
Route::resource('/manage-konsumen', KonsumenController::class);
Route::get('/tambahkonsumen', [KonsumenController::class, 'tambahkonsumen'])->name('konsumen.tambahkonsumen');
Route::get('dbbackup', [DBBackupController::class, 'DBDataBackup']);
Route::get('/penawaran', [PenawaranController::class, 'index'])->name('penawaran.index');
Route::get('/penawaran/create', [PenawaranController::class, 'create'])->name('penawaran.create');
Route::post('/action_penawaran', [ActionPenawaran::class, 'tambahPenawaran']);
Route::post('/penawaran', [PenawaranController::class, 'store'])->name('penawaran.store');
Route::get('/penawaran/{id}/edit', [PenawaranController::class, 'edit'])->name('penawaran.edit');
Route::delete('/penawaran/{id}', [PenawaranController::class, 'destroy'])->name('penawaran.destroy');
Route::get('/penawaran/{id}/detail', [PenawaranController::class, 'show'])->name('penawaran.show');
Route::get('penawaran/{id}/konfirmasi', 'PenawaranController@konfirmasi')->name('penawaran.konfirmasi');
Route::get('penawaran/{id}/detail', 'PenawaranController@show')->name('penawaran.detail');


Route::resource('suratjalan', SuratJalanController::class);
Route::put('suratjalan/{suratjalan}/confirm', [SuratJalanController::class, 'confirm'])->name('suratjalan.confirm');
Route::post('/suratjalan', [SuratJalanController::class, 'store'])->name('suratjalan.store');

Route::get('purchaseorder/{id}/unduh', [PurchaseOrderController::class, 'unduh'])->name('purchaseorder.unduh');
Route::get('/purchaseorder/{id}/info', [PurchaseOrderController::class, 'info'])->name('purchaseorder.info');


Route::resource('detail', DetailPenawaranController::class)->only(['edit', 'update', 'destroy']);
Route::resource('penawaran', PenawaranController::class);
Route::get('penawaran/{id}/konfirmasi', [PenawaranController::class, 'konfirmasi'])->name('penawaran.konfirmasi');
Route::post('/purchaseorder/{id}/update-status', [PurchaseOrderController::class, 'updateStatus'])->name('purchaseorder.updateStatus');
Route::post('/purchaseorder/{id}/create-suratjalan', [PurchaseOrderController::class, 'createSuratJalan'])->name('purchaseorder.createSuratJalan');
Route::get('/suratjalan/create', [SuratJalanController::class, 'create'])->name('suratjalan.create');
Route::get('/purchaseorder/{id}/create-suratjalan', [SuratJalanController::class, 'create'])->name('suratjalan.create');
Route::get('/purchaseorder/{id}/detail', 'PurchaseorderController@show')->name('purchaseorder.detail');
Route::get('/suratjalan/{id}/detail', [PurchaseorderController::class,'huft'])->name('purchaseorder.huft');

// Route untuk menyimpan surat jalan
Route::post('/suratjalan', [SuratJalanController::class, 'store'])->name('suratjalan.store');
Route::resource('purchaseorder', PurchaseOrderController::class);
Route::resource('suratjalan', SuratJalanController::class);

Route::post('purchaseorder/{id}/create-suratjalan', [PurchaseOrderController::class, 'createSuratJalan'])->name('purchaseorder.createSuratJalan');
Route::put('/suratjalan/{id}', 'SuratJalanController@update')->name('suratjalan.update');

Route::get('penawaran/{id}/unduh', [PenawaranController::class, 'unduh'])->name('penawaran.unduh');
Route::get('suratjalan/{id}/unduh', [SuratJalanController::class, 'unduh'])->name('suratjalan.unduh');
Route::get('/purchaseorder/{id}/create-suratjalan', [PurchaseOrderController::class, 'createSuratJalan'])->name('purchaseorder.createSuratJalan');

Route::get('/suratjalan/{id}', 'SuratJalanController@show')->name('suratjalan.show');
Route::get('/purchaseorder/{id}', 'PurchaseorderController@show')->name('suratjalan.show');

app/Models/Barang.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Barang extends Model
{
    use HasFactory;

    protected $table = 'barang';
    protected $fillable = ['nama', 'deskripsi', 'harga', 'stok'];

    public function fotos()
    {
        return $this->hasMany(BarangFoto::class);
    }

    public function penawarans()
    {
        return $this->belongsToMany(Penawaran::class, 'detail_penawarans')->withPivot('kuantitas', 'harga');
    }

    public function detailPenawaran()
    {
        return $this->hasMany(DetailPenawaran::class, 'id_barang');
    }
    public function detailPurchaseOrders()
    {
        return $this->hasMany(DetailPurchaseOrder::class, 'id_barang', 'id');
    }
}

app/Http/Controllers/BarangController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Barang;
use App\Models\BarangFoto;
use Illuminate\Support\Facades\Storage;
use App\Models\Penawaran; 

class BarangController extends Controller
{
    // Method untuk menampilkan daftar barang
    public function index()
    {
        $barang = Barang::all();
        return view('barang.index', compact('barang'));
    }

    // Method untuk menampilkan form create
    public function create()
    {
        return view('barang.create');
    }

    // Method untuk menyimpan barang baru
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'nama' => 'required|string|max:255',
            'deskripsi' => 'required|string',
            'harga' => 'required|numeric',
            'stok' => 'required|numeric',
            'foto.*' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        $barang = Barang::create($validatedData);

        // Handle multiple file uploads
        if ($request->hasFile('foto')) {
            foreach ($request->file('foto') as $file) {
                $path = $file->store('public/uploads');
                $foto = new BarangFoto();
                $foto->barang_id = $barang->id;
                $foto->path = $file->hashName();
                $foto->save();
            }
        }

        return redirect()->route('manage-barang.index')->with('success', 'Barang berhasil ditambahkan');
    }

    // Method untuk menampilkan form edit
    public function edit($id)
    {
        $barang = Barang::findOrFail($id);
        return view('barang.edit', compact('barang'));
    }

    // Method untuk mengupdate barang
    public function update(Request $request, $id)
{
    $validatedData = $request->validate([
        'nama' => 'required|string|max:255',
        'deskripsi' => 'required|string',
        'harga' => 'required|numeric',
        'stok' => 'required|numeric',
        'foto.*' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
    ]);

    $barang = Barang::findOrFail($id);
    $barang->update($validatedData);

    // Handle photo updates
    if ($request->hasFile('foto')) {
        // Delete existing photos if needed
        $barang->fotos()->delete();

        // Upload new photos
        foreach ($request->file('foto') as $file) {
            $path = $file->store('public/uploads');
            $foto = new BarangFoto();
            $foto->barang_id = $barang->id;
            $foto->path = $file->hashName(); // or use $path if you want full path
            $foto->save();
        }
    }

    return redirect()->route('manage-barang.index')->with('success', 'Barang berhasil diperbarui');
}

public function destroy($id)
{
    $barang = Barang::findOrFail($id);
    
    // Delete associated photos
    $fotos = $barang->fotos;
    foreach ($fotos as $foto) {
        $filePath = storage_path('app/public/' . $foto->path);
        if (file_exists($filePath)) {
            unlink($filePath);
        }
        $foto->delete();
    }

    // Delete associated detail_purchase_order
    $detailPurchaseOrders = $barang->detailPurchaseOrders;
    foreach ($detailPurchaseOrders as $detailPurchaseOrder) {
        $detailPurchaseOrder->delete();
    }

    $barang->delete();

    return redirect()->route('manage-barang.index')->with('success', 'Barang berhasil dihapus');
}


}

resources/views/barang/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container d-flex flex-column gap-5 p-3">
    <div class="row mb-2">
        <div class="col-sm-6">
            <h3 class="text-bold">Tambah Barang</h3>
        </div>
        <div class="col-sm-6">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Daftar Barang</li>
                    <li class="breadcrumb-item active">Tambah Barang</li>
                </ol>
            </nav>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form id="barangForm" action="{{ route('manage-barang.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group">
                            <label for="nama">Nama Barang</label>
                            <input type="text" name="nama" class="form-control" required>
                        </div>

                        <div class="form-group">
                            <label for="deskripsi">Deskripsi</label>
                            <textarea name="deskripsi" class="form-control" required></textarea>
                        </div>

                        <div class="form-group">
                            <label for="harga">Harga</label>
                            <input type="text" name="harga" id="harga" class="form-control" required>
                        </div>

                        <div class="form-group">
                            <label for="stok">Stok</label>
                            <input type="number" name="stok" class="form-control" required>
                        </div>

                        <div class="form-group">
                            <label for="foto">Foto Barang</label>
                            <small class="form-text text-muted">Dapat memilih lebih dari 1 barang</small>
                            <div class="custom-file">
                                <input type="file" name="foto[]" id="image-uploader" class="custom-file-input" multiple>
                                <label class="custom-file-label" for="image-uploader">Pilih file...</label>
                            </div>
                            <div id="image-preview" class="mt-3"></div>
                        </div>

                        <button type="submit" class="btn btn-primary mt-3">Tambah Barang</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        $('#image-uploader').on('change', function() {
            $('#image-preview').html('');
            const files = this.files;
            if (files.length > 0) {
                for (let i = 0; i < files.length; i++) {
                    const file = files[i];
                    const reader = new FileReader();
                    reader.onload = function(e) {
                        // Create image element
                        const img = $('<img>').attr('src', e.target.result).css({
                            'width': '150px',
                            'height': 'auto',
                            'margin': '10px',
                        });

                        // Create remove button
                        const removeBtn = $('<div>').addClass('cancel-btn').html('<i class="fa fa-times-circle"></i>').click(function() {
                            $(this).parent().remove();
                        });

                        // Create preview container
                        const previewContainer = $('<div>').addClass('preview-container').css({
                            'display': 'grid',
                            'grid-template-columns': 'repeat(auto-fit, minmax(150px, 1fr))',
                            'gap': '10px',
                            'position': 'relative',
                        }).append(img);

                        // Style remove button
                        removeBtn.css({
                            'position': 'absolute',
                            'top': '10px',
                            'left': '140px',
                            'z-index': '1',
                            'cursor': 'pointer',
                        });

                        // Append remove button to preview container
                        previewContainer.append(removeBtn);

                        // Append preview container to image preview div
                        $('#image-preview').append(previewContainer);
                    };
                    reader.readAsDataURL(file);
                }
            }
        });
    });
</script>

<script>
    function formatCurrency(value) {
        return 'Rp.' + parseFloat(value.replace(/[^0-9]/g, '')).toLocaleString('id-ID');
    }

    document.addEventListener('DOMContentLoaded', function() {
        const hargaInput = document.getElementById('harga');

        hargaInput.addEventListener('input', function(e) {
            let value = e.target.value.replace(/[^0-9]/g, '');
            if (value) {
                e.target.value = formatCurrency(value);
            } else {
                e.target.value = '';
            }
        });

        document.getElementById('barangForm').addEventListener('submit', function() {
            hargaInput.value = hargaInput.value.replace(/[^0-9]/g, '');
        });
    });
</script>
@endpush

resources/views/barang/edit.blade.php
@extends('layouts.app')
@push('css')
@endpush
@section('content')
<div class="container d-flex flex-column gap-5 p-3">
    <div class="row mb-2">
        <div class="col-sm-6">
            <h3 class="text-bold">Edit Barang</h3>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">Daftar Barang</li>
                <li class="breadcrumb-item active">Edit Barang</li>
            </ol>
        </div>
    </div>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h5 class="card-title m-0">Edit Barang</h5>
                            <div class="card-tools">
                                <a href="{{ route('manage-barang.index') }}" class="btn btn-tool"><i class="fas fa-arrow-alt-circle-left"></i></a>
                            </div>
                        </div>
                        <form action="{{ route('barang.update', $barang->id) }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="nama">Nama Barang</label>
                                    <input type="text" name="nama" class="form-control @error('nama') is-invalid @enderror" value="{{ $barang->nama }}" required>
                                    @error('nama')
                                    <div class="invalid-feedback" role="alert">
                                        <span>{{ $message }}</span>
                                    </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="deskripsi">Deskripsi</label>
                                    <textarea name="deskripsi" class="form-control @error('deskripsi') is-invalid @enderror" required>{{ $barang->deskripsi }}</textarea>
                                    @error('deskripsi')
                                    <div class="invalid-feedback" role="alert">
                                        <span>{{ $message }}</span>
                                    </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="harga">Harga</label>
                                    <input type="number" name="harga" class="form-control @error('harga') is-invalid @enderror" value="{{ $barang->harga }}" required>
                                    @error('harga')
                                    <div class="invalid-feedback" role="alert">
                                        <span>{{ $message }}</span>
                                    </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="stok">Stok</label>
                                    <input type="number" name="stok" class="form-control @error('stok') is-invalid @enderror" value="{{ $barang->stok }}" required>
                                    @error('stok')
                                    <div class="invalid-feedback" role="alert">
                                        <span>{{ $message }}</span>
                                    </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="foto">Foto Barang</label>
                                    <input type="file" name="foto[]" id="foto" class="form-control @error('foto.*') is-invalid @enderror" multiple>
                                    
                                    @if($barang->fotos->count() > 0)
                                        <div id="image-preview" class="mt-3">
                                            @foreach($barang->fotos as $foto)
                                                <div class="preview-container">
                                                    {{-- <img src="{{ asset('public/storage/uploads' . $foto->path) }}" alt="Foto Barang" style="height: 150px; width: auto;">
                                                    <button type="button" class="btn btn-sm btn-danger mt-2 remove-btn">Remove</button> --}}
                                                </div>
                                            @endforeach
                                        </div>
                                    @else
                                        <div id="image-preview" class="mt-3" style="display: none;"></div>
                                    @endif
                                    
                                    @error('foto.*')
                                        <div class="invalid-feedback" role="alert">
                                            <span>{{ $message }}</span>
                                        </div>
                                    @enderror
                                </div>
                                
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Update Barang</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
       $(document).ready(function() {
    $('#foto').on('change', function(e) {
        $('#image-preview').html('');
        const files = this.files;
        if (files.length > 0) {
            for (let i = 0; i < files.length; i++) {
                const file = files[i];
                const reader = new FileReader();
                reader.onload = function(e) {
                    // Create image element
                    const img = $('<img>').attr('src', e.target.result).css({
                        'width': '150px',
                        'height': 'auto',
                        'margin': '10px',
                    });

                    // Create remove button
                    const removeBtn = $('<div>').addClass('cancel-btn').html('<i class="fa fa-times-circle"></i>').click(function() {
                        $(this).parent().remove(); // Remove the preview container when remove button is clicked
                    });

                    // Create preview container
                    const previewContainer = $('<div>').addClass('preview-container').css({
                        'display': 'grid',
                        'grid-template-columns': 'repeat(auto-fit, minmax(150px, 1fr))',
                        'gap': '10px',
                        'position': 'relative',
                    }).append(img);

                    // Style remove button
                    removeBtn.css({
                        'position': 'absolute',
                        'top': '12px',
                        'left': '138px',
                        'z-index': '1',
                        'cursor': 'pointer',
                        'color': 'red',
                    });

                    // Append remove button to preview container
                    previewContainer.append(removeBtn);

                    // Append preview container to image preview div
                    $('#image-preview').append(previewContainer);
                };
                reader.readAsDataURL(file);
            }
            $('#image-preview').show(); // Show the image preview
        } else {
            $('#image-preview').hide(); // Hide the image preview if no files selected
        }
    });
});
</script>
@endpush

resources/views/barang/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container d-flex flex-column gap-5 p-3">
    <div class="row mb-2">
        <div class="col-sm-6">
            <h3 class="text-bold">Daftar Barang</h3>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">Daftar Barang</li>
            </ol>
        </div>
    </div>

    <div class="row mb-1">
        <div class="col-8 col-md-3 card card-outline">
            <div class="card-header">
                <h5 class="m-0 text-bold">Tambah Barang</h5>
            </div>
            <div class="card-body">
                <a class="btn btn-info text-bold col-sm-12 col-md d-flex flex-column align-items-center" href="{{ route('manage-barang.create') }}"><i class="fas fa-tags"></i>Tambah Barang</a>
            </div>
        </div>
    </div>

    <!-- Tabel Daftar Barang -->
    <div class="row mb-1">
        <div class="col-12 card card-outline">
            <div class="card-body" style="overflow: auto">
                <table id="dataTable" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nama</th>
                            <th scope="col">Deskripsi</th>
                            <th scope="col">Harga</th>
                            <th scope="col">Stok</th>
                            <th scope="col">Foto</th>
                            <th scope="col">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php $number = 1 @endphp
                        @foreach($barang as $item)
                        <tr>
                            <th scope="row">{{ $number++ }}</th>
                            <td>{{ $item->nama }}</td>
                            <!-- Menyesuaikan lebar kolom deskripsi -->
                            <td style="width: 30%;">{{ $item->deskripsi }}</td>
                            <td class="harga">{{ $item->harga }}</td>
                            <td>{{ $item->stok }}</td>
                            <td>
                                @foreach($item->fotos as $foto)
                                <img src="{{ asset('storage/uploads/' . $foto->path) }}" alt="Foto Barang" style="height: 150px; width: auto; margin-bottom: 10px;">
                                @endforeach
                            </td>
                            <!-- Menyesuaikan lebar kolom aksi -->
                            <td style="width: 100px;" class="NoPrint col-md-4">
                                <!-- Dropdown untuk Aksi -->
                                <div class="dropdown">
                                    <button type="button" class="btn btn-sm btn-outline-info dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                        <i class="fas fa-cog"></i>
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-up">
                                        <a class="dropdown-item" href="{{ route('manage-barang.edit', $item->id) }}">Edit</a>
                                        <form action="{{ route('manage-barang.destroy', $item->id) }}" method="POST" style="display: inline;">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="dropdown-item" onclick="return confirm('Apakah Anda yakin ingin menghapus barang ini?')">Hapus</button>
                                        </form>
                                        <!-- Tambahkan aksi lainnya sesuai kebutuhan -->
                                    </div>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap4.min.js"></script>
<script>
    $(document).ready(function() {
        $('#dataTable').DataTable();

        function formatCurrency(value) {
            return 'Rp.' + parseFloat(value).toLocaleString('id-ID', {
                minimumFractionDigits: 2,
                maximumFractionDigits: 2
            });
        }

        $('#dataTable tbody .harga').each(function() {
            const originalValue = $(this).text();
            $(this).text(formatCurrency(originalValue));
        });
    });
</script>
@endpush

resources/views/barang/tambahbarang.blade.php
@extends('layouts.app')

@section('content')
<div class="p-3">
  <div class="card card-warning">
    <div class="card-header">
      <h3 class="card-title">Tambah Barang</h3>
    </div>
    <div class="card-body">
      <div class="form-group">
        <label for="inputName">Id</label>
        <input type="text" id="inputName" class="form-control">
      </div>
      <div class="form-group">
        <label for="inputName">Nama</label>
        <input type="text" id="inputName" class="form-control">
      </div>
      <div class="form-group">
        <label for="inputName">Deskripsi</label>
        <input type="text" id="inputName" class="form-control">
      </div>
      <div class="form-group">
        <label for="inputName">Harga</label>
        <input type="number" id="inputName" class="form-control">
      </div>
      <div class="form-group">
        <label for="inputName">Stock</label>
        <input type="number" id="inputName" class="form-control">
      </div>
      <div class="form-group">
        <label for="inputName">Foto</label>
        <input type="image" id="inputName" class="form-control">
      </div>
<div class="row p-3">
  <div class="col-12">
    <a href="/manage-konsumen" class="btn btn-danger">Cancel</a>
    <input type="submit" value="Tambah Konsumen" class="btn btn-warning float-right">
  </div>
</div>

@endsection